# Generated by Django 3.1.7 on 2021-03-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_base_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('product_description', models.TextField()),
                ('product_start_time', models.DateTimeField()),
                ('product_end_time', models.DateTimeField()),
                ('product_updated_at', models.DateField()),
                ('product_status', models.CharField(choices=[('sold', 'sold'), ('unsold', 'unsold')], default='unsold', max_length=20)),
                ('product_sold_to', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='media/product/%Y/%m')),
                ('product_created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
